### ISSUE TITLE
Failed to find scheme archivable target

### ISSUE THREAD

**Issue by yonaskolb** [bitrise-steplib/steps-ios-auto-provision#18]
I'm getting an error in this step. Log is below
Note that we're using Automatic signing in Xcode. Is this supported?

```sh
+------------------------------------------------------------------------------+
| (6) ios-auto-provision@0.9.7                                                 |
+------------------------------------------------------------------------------+
| id: ios-auto-provision                                                       |
| version: 0.9.7                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2018-02-28T20:39:47-08:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
$ bundle install
$ bundle exec ruby /var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise247414974/step_src/step.rb
Params:
team_id: 3PU2FX2MA5
certificate_urls: ***
passphrases: 
distribution_type: ad-hoc
project_path: Axis.xcodeproj
scheme: Axis_iOS QA2
configuration: 
build_url: https://www.bitrise.io/build/77eeabf1c133195f
build_api_token: ***
keychain_path: /Users/vagrant/Library/Keychains/login.keychain
keychain_password: ***
verbose_log: no
Developer Portal authentication
authenticated
Downloading Certificates
1 certificate files downloaded, 2 codesign identities included
Identify Certificates on developer Portal
production Certificate identified: iOS Distribution
provided an older version of iPhone Developer: Yonas Kolb (XY7TEP9H45) certificate, please provide the most recent version of the certificate
provided an older version of iPhone Developer: Yonas Kolb (XY7TEP9H45) certificate, please provide the most recent version of the certificate
provided an older version of iPhone Developer: Yonas Kolb (XY7TEP9H45) certificate, please provide the most recent version of the certificate
development Certificate identified: iOS Development
Analyzing project
Error:
failed to find scheme archivable target
Stacktrace (for debugging):
/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise247414974/step_src/project_helper/project_helper.rb:260:in `read_scheme_archivable_target_and_container_project'
/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise247414974/step_src/project_helper/project_helper.rb:23:in `initialize'
/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise247414974/step_src/step.rb:200:in `new'
/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise247414974/step_src/step.rb:200:in `<main>'
```

**Comment by viktorbenei** [comment]
Thanks for reporting the issue @yonaskolb , we'll look into it ASAP! :)

**Comment by yonaskolb** [comment]
Interesting I changed the distribution type to `app-store` and am now getting a different error:
`undefined method `[]=' for nil:NilClass` within `step_src/project_helper/project_helper.rb:169:in `block in force_code_sign_properties`

Full log:
```
+------------------------------------------------------------------------------+

| (0) ios-auto-provision@0.9.7                                                 |
+------------------------------------------------------------------------------+
| id: ios-auto-provision                                                       |
| version: 0.9.7                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2018-03-04T18:30:56-08:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
$ bundle install
$ bundle exec ruby /var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise055477342/step_src/step.rb
Params:
team_id: 3PU2FX2MA5
certificate_urls: ***
passphrases: 
distribution_type: app-store
project_path: Axis.xcodeproj
scheme: Axis_iOS QA2
configuration: 
build_url: https://www.bitrise.io/build/5b783f57478c0721
build_api_token: ***
keychain_path: /Users/vagrant/Library/Keychains/login.keychain
keychain_password: ***
verbose_log: no
Developer Portal authentication
authenticated
Downloading Certificates
1 certificate files downloaded, 2 codesign identities included
Identify Certificates on developer Portal
production Certificate identified: iOS Distribution
provided an older version of iPhone Developer: Yonas Kolb (XY7TEP9H45) certificate, please provide the most recent version of the certificate
provided an older version of iPhone Developer: Yonas Kolb (XY7TEP9H45) certificate, please provide the most recent version of the certificate
provided an older version of iPhone Developer: Yonas Kolb (XY7TEP9H45) certificate, please provide the most recent version of the certificate
development Certificate identified: iOS Development
Analyzing project
project codesign identity: iPhone Developer
project team id: 3PU2FX2MA5
target #0: Axis_iOS (co.massive.axis.qa2) with 0 services
Matching project codesign identity with the uploaded certificates
using: iPhone Developer: Yonas Kolb (XY7TEP9H45)
using: iPhone Distribution: Massive Interactive Pty Ltd (3PU2FX2MA5)
Ensure App IDs and Provisioning Profiles on Developer Portal
checking target: Axis_iOS (co.massive.axis.qa2) with 0 services
ensure App ID (co.massive.axis.qa2) on Developer Portal
app already registered: XC co massive axis qa2 with bundle id: co.massive.axis.qa2
sync App ID (co.massive.axis.qa2) Services
ensure Development Provisioning Profile on Developer Portal
generating development profile: Bitrise development - (co.massive.axis.qa2)
generating development profile: Bitrise development - (co.massive.axis.qa2)
downloading development profile: Bitrise development - (co.massive.axis.qa2)
ensure Production Provisioning Profile on Developer Portal
generating app-store profile: Bitrise app-store - (co.massive.axis.qa2)
generating app-store profile: Bitrise app-store - (co.massive.axis.qa2)
downloading app-store profile: Bitrise app-store - (co.massive.axis.qa2)
Apply code sign setting in project
configure target: Axis_iOS (co.massive.axis.qa2)
Error:
undefined method `[]=' for nil:NilClass
Stacktrace (for debugging):
/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise055477342/step_src/project_helper/project_helper.rb:169:in `block in force_code_sign_properties'
/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise055477342/step_src/project_helper/project_helper.rb:161:in `each'
/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise055477342/step_src/project_helper/project_helper.rb:161:in `force_code_sign_properties'
/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise055477342/step_src/step.rb:375:in `block in <main>'
/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise055477342/step_src/step.rb:355:in `each'
/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise055477342/step_src/step.rb:355:in `<main>'
```

**Comment by yonaskolb** [comment]
I think the fix for the second error is to just provide an empty `target_attributes` if one isn't found on the project.

**Comment by godrei** [comment]
Hi @yonaskolb , could you please try the new version: [1.0.0](https://github.com/bitrise-steplib/steps-ios-auto-provision/releases/tag/1.0.0)? Your issue still exist?

**Comment by yonaskolb** [comment]
Hi @godrei. Yep, still getting that issue. The exact same one as logged in #20

**Comment by godrei** [comment]
@yonaskolb could you please write us a message on bitrise.io on site chat? i would need to have a look on your .xcodeproj file to debug the target_attributes issue.

**Comment by godrei** [comment]
Hi @yonaskolb ,
we released a new version: [1.0.1](https://github.com/bitrise-steplib/steps-ios-auto-provision/releases/tag/1.0.1), which should fix this problem.
I'll close this issue, but if you need more info/help just let us know and we'll reopen it!

**Comment by talezion** [comment]
I am still getting this issue with the latest release.

**Comment by godrei** [comment]
@talezion we discussed the issue on bitrise.io on-site-chat and it seems the issue is resolved by some project updates.

I'll close this issue, but if you need more info/help just let us know and we'll reopen it!

**Comment by MikeGlotov** [comment]
Still an issue for me. Chated about it on a website, no results. I think there is a support ticket created by your support desk

**Comment by non-binary** [comment]
@MikeGlotov How did you solve this?

**Comment by MikeGlotov** [comment]
@non-binary didn't solve it. I've sticked to manual signing :(
